# GNU Make project makefile autogenerated by Premake

ifndef config
  config=release_x86_64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),release_x86_64)
  RESCOMP = windres
  TARGETDIR = x86_64/Release
  TARGET = $(TARGETDIR)/gmcl_io_events_linux64.dll
  OBJDIR = x86_64/Release/intermediate/gmcl_io_events
  DEFINES += -DNDEBUG -DGMMODULE -DIO_EVENTS_CLIENT -DIS_SERVERSIDE=false -DGMOD_USE_SOURCESDK -DCLIENT_DLL -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DNO_MALLOC_OVERRIDE
  INCLUDES += -I../../../include -I../../../source -isystem ../../../../garrysmod_common/include -isystem ../../../../sourcesdk-minimal/common -isystem ../../../../sourcesdk-minimal/public -isystem ../../../../sourcesdk-minimal/game/client -isystem ../../../../sourcesdk-minimal/game/shared -isystem ../../../../sourcesdk-minimal/public/tier0 -isystem ../../../../sourcesdk-minimal/public/tier1
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../garrysmod_common/projects/linux/gmake/x86_64/Release/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86_64/Release/libtier1.a -ltier0 -lvstdlib
  LDDEPS += ../../../../garrysmod_common/projects/linux/gmake/x86_64/Release/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86_64/Release/libtier1.a
  ALL_LDFLAGS += $(LDFLAGS) -L../../../../sourcesdk-minimal/lib/public/linux32 -L/usr/lib64 -m64 -flto -shared -Wl,-soname=gmcl_io_events_linux64.dll
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_x86)
  RESCOMP = windres
  TARGETDIR = x86/Release
  TARGET = $(TARGETDIR)/gmcl_io_events_linux.dll
  OBJDIR = x86/Release/intermediate/gmcl_io_events
  DEFINES += -DNDEBUG -DGMMODULE -DIO_EVENTS_CLIENT -DIS_SERVERSIDE=false -DGMOD_USE_SOURCESDK -DCLIENT_DLL -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DNO_MALLOC_OVERRIDE
  INCLUDES += -I../../../include -I../../../source -isystem ../../../../garrysmod_common/include -isystem ../../../../sourcesdk-minimal/common -isystem ../../../../sourcesdk-minimal/public -isystem ../../../../sourcesdk-minimal/game/client -isystem ../../../../sourcesdk-minimal/game/shared -isystem ../../../../sourcesdk-minimal/public/tier0 -isystem ../../../../sourcesdk-minimal/public/tier1
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../garrysmod_common/projects/linux/gmake/x86/Release/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86/Release/libtier1.a -ltier0 -lvstdlib
  LDDEPS += ../../../../garrysmod_common/projects/linux/gmake/x86/Release/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86/Release/libtier1.a
  ALL_LDFLAGS += $(LDFLAGS) -L../../../../sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -flto -shared -Wl,-soname=gmcl_io_events_linux.dll
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),releasewithsymbols_x86_64)
  RESCOMP = windres
  TARGETDIR = x86_64/ReleaseWithSymbols
  TARGET = $(TARGETDIR)/gmcl_io_events_linux64.dll
  OBJDIR = x86_64/ReleaseWithSymbols/intermediate/gmcl_io_events
  DEFINES += -DNDEBUG -DGMMODULE -DIO_EVENTS_CLIENT -DIS_SERVERSIDE=false -DGMOD_USE_SOURCESDK -DCLIENT_DLL -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DNO_MALLOC_OVERRIDE
  INCLUDES += -I../../../include -I../../../source -isystem ../../../../garrysmod_common/include -isystem ../../../../sourcesdk-minimal/common -isystem ../../../../sourcesdk-minimal/public -isystem ../../../../sourcesdk-minimal/game/client -isystem ../../../../sourcesdk-minimal/game/shared -isystem ../../../../sourcesdk-minimal/public/tier0 -isystem ../../../../sourcesdk-minimal/public/tier1
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../garrysmod_common/projects/linux/gmake/x86_64/ReleaseWithSymbols/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86_64/ReleaseWithSymbols/libtier1.a -ltier0 -lvstdlib
  LDDEPS += ../../../../garrysmod_common/projects/linux/gmake/x86_64/ReleaseWithSymbols/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86_64/ReleaseWithSymbols/libtier1.a
  ALL_LDFLAGS += $(LDFLAGS) -L../../../../sourcesdk-minimal/lib/public/linux32 -L/usr/lib64 -m64 -shared -Wl,-soname=gmcl_io_events_linux64.dll
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),releasewithsymbols_x86)
  RESCOMP = windres
  TARGETDIR = x86/ReleaseWithSymbols
  TARGET = $(TARGETDIR)/gmcl_io_events_linux.dll
  OBJDIR = x86/ReleaseWithSymbols/intermediate/gmcl_io_events
  DEFINES += -DNDEBUG -DGMMODULE -DIO_EVENTS_CLIENT -DIS_SERVERSIDE=false -DGMOD_USE_SOURCESDK -DCLIENT_DLL -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DNO_MALLOC_OVERRIDE
  INCLUDES += -I../../../include -I../../../source -isystem ../../../../garrysmod_common/include -isystem ../../../../sourcesdk-minimal/common -isystem ../../../../sourcesdk-minimal/public -isystem ../../../../sourcesdk-minimal/game/client -isystem ../../../../sourcesdk-minimal/game/shared -isystem ../../../../sourcesdk-minimal/public/tier0 -isystem ../../../../sourcesdk-minimal/public/tier1
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../garrysmod_common/projects/linux/gmake/x86/ReleaseWithSymbols/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86/ReleaseWithSymbols/libtier1.a -ltier0 -lvstdlib
  LDDEPS += ../../../../garrysmod_common/projects/linux/gmake/x86/ReleaseWithSymbols/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86/ReleaseWithSymbols/libtier1.a
  ALL_LDFLAGS += $(LDFLAGS) -L../../../../sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -shared -Wl,-soname=gmcl_io_events_linux.dll
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_x86_64)
  RESCOMP = windres
  TARGETDIR = x86_64/Debug
  TARGET = $(TARGETDIR)/gmcl_io_events_linux64.dll
  OBJDIR = x86_64/Debug/intermediate/gmcl_io_events
  DEFINES += -DDEBUG -D_DEBUG -DGMMODULE -DIO_EVENTS_CLIENT -DIS_SERVERSIDE=false -DGMOD_USE_SOURCESDK -DCLIENT_DLL -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DNO_MALLOC_OVERRIDE
  INCLUDES += -I../../../include -I../../../source -isystem ../../../../garrysmod_common/include -isystem ../../../../sourcesdk-minimal/common -isystem ../../../../sourcesdk-minimal/public -isystem ../../../../sourcesdk-minimal/game/client -isystem ../../../../sourcesdk-minimal/game/shared -isystem ../../../../sourcesdk-minimal/public/tier0 -isystem ../../../../sourcesdk-minimal/public/tier1
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -O0 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -O0 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../garrysmod_common/projects/linux/gmake/x86_64/Debug/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86_64/Debug/libtier1.a -ltier0 -lvstdlib
  LDDEPS += ../../../../garrysmod_common/projects/linux/gmake/x86_64/Debug/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86_64/Debug/libtier1.a
  ALL_LDFLAGS += $(LDFLAGS) -L../../../../sourcesdk-minimal/lib/public/linux32 -L/usr/lib64 -m64 -shared -Wl,-soname=gmcl_io_events_linux64.dll
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_x86)
  RESCOMP = windres
  TARGETDIR = x86/Debug
  TARGET = $(TARGETDIR)/gmcl_io_events_linux.dll
  OBJDIR = x86/Debug/intermediate/gmcl_io_events
  DEFINES += -DDEBUG -D_DEBUG -DGMMODULE -DIO_EVENTS_CLIENT -DIS_SERVERSIDE=false -DGMOD_USE_SOURCESDK -DCLIENT_DLL -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DNO_MALLOC_OVERRIDE
  INCLUDES += -I../../../include -I../../../source -isystem ../../../../garrysmod_common/include -isystem ../../../../sourcesdk-minimal/common -isystem ../../../../sourcesdk-minimal/public -isystem ../../../../sourcesdk-minimal/game/client -isystem ../../../../sourcesdk-minimal/game/shared -isystem ../../../../sourcesdk-minimal/public/tier0 -isystem ../../../../sourcesdk-minimal/public/tier1
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -O0 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -O0 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../garrysmod_common/projects/linux/gmake/x86/Debug/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86/Debug/libtier1.a -ltier0 -lvstdlib
  LDDEPS += ../../../../garrysmod_common/projects/linux/gmake/x86/Debug/liblua_shared.a ../../../../garrysmod_common/projects/linux/gmake/x86/Debug/libtier1.a
  ALL_LDFLAGS += $(LDFLAGS) -L../../../../sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -shared -Wl,-soname=gmcl_io_events_linux.dll
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/main.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking gmcl_io_events
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning gmcl_io_events
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/main.o: ../../../source/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif